apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  AWS_APPSYNC_GRAPHQL_ENDPOINT: https://gz27nh6fzra3hmxw7nulijnzw4.appsync-api.ap-northeast-2.amazonaws.com/graphql
  AWS_APPSYNC_APIKEY: da2-kiapkzfjgbbxfai47elh4fbaxa
