apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aws-prototype-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: aws-prototype-ingress
spec:
  rules:
    - http:
        paths:
          - path: /auth/*
            backend:
              serviceName: app-service
              servicePort: 8001
          - path: /product/*
            backend:
              serviceName: app-service
              servicePort: 8000